# Generated by Django 2.2.6 on 2020-01-19 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_auto_20200117_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw', models.TextField()),
                ('sender', models.CharField(max_length=200)),
                ('reported', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reciever', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
