# Generated by Django 2.2.6 on 2020-01-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalClassified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('total_reported', models.IntegerField(default=0)),
            ],
        ),
    ]
